export const danhSachNhanVien = [
    { id: 'NV001', name: 'Nguyễn Văn An', department: 'IT', role: 'Senior Developer', salary: 25000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV002', name: 'Trần Thị Bích', department: 'HR', role: 'HR Manager', salary: 28000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV003', name: 'Lê Minh Cường', department: 'Marketing', role: 'Digital Marketer', salary: 18000000, status: 'Đang làm', attendance: 22, },
    { id: 'NV004', name: 'Phạm Thị Dung', department: 'Sales', role: 'Sales Executive', salary: 12000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV005', name: 'Hoàng Văn Giang', department: 'IT', role: 'UI/UX Designer', salary: 22000000, status: 'Đang làm', attendance: 23, },
    { id: 'NV006', name: 'Vũ Thị Hà', department: 'Accounting', role: 'Accountant', salary: 16000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV007', name: 'Đỗ Tuấn Hùng', department: 'IT', role: 'Junior Developer', salary: 10000000, status: 'Đang làm', attendance: 20, },
    { id: 'NV008', name: 'Ngô Thị Lan', department: 'HR', role: 'Recruiter', salary: 14000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV009', name: 'Trịnh Văn Mạnh', department: 'Sales', role: 'Sales Leader', salary: 30000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV010', name: 'Bùi Thị Oanh', department: 'Marketing', role: 'Content Creator', salary: 13000000, status: 'Đang làm', attendance: 21, },
    { id: 'NV011', name: 'Lý Công Tuấn', department: 'IT', role: 'Intern', salary: 5000000, status: 'Nghỉ việc', attendance: 18, },
    { id: 'NV012', name: 'Mai Anh Đào', department: 'Accounting', role: 'Chief Accountant', salary: 35000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV013', name: 'Dương Minh Khôi', department: 'Operations', role: 'Operations Manager', salary: 27000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV014', name: 'Phan Thanh Tùng', department: 'IT', role: 'DevOps Engineer', salary: 26000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV015', name: 'Đặng Ngọc Mai', department: 'Marketing', role: 'SEO Specialist', salary: 19000000, status: 'Đang làm', attendance: 23, },
    { id: 'NV016', name: 'Hồ Bảo Trâm', department: 'Sales', role: 'Account Manager', salary: 20000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV017', name: 'Nguyễn Quốc Bảo', department: 'IT', role: 'QA Engineer', salary: 17000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV018', name: 'Lê Thị Thu Thảo', department: 'HR', role: 'C&B Specialist', salary: 18000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV019', name: 'Võ Minh Quân', department: 'Operations', role: 'Logistics Coordinator', salary: 15000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV020', name: 'Trần Đức Anh', department: 'IT', role: 'Project Manager', salary: 32000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV021', name: 'Huỳnh Kim Ngân', department: 'Accounting', role: 'Auditor', salary: 19000000, status: 'Đang làm', attendance: 23, },
    { id: 'NV022', name: 'Phạm Gia Huy', department: 'Marketing', role: 'Marketing Manager', salary: 35000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV023', name: 'Nguyễn Thảo Nguyên', department: 'Sales', role: 'Sales Intern', salary: 4000000, status: 'Nghỉ việc', attendance: 15, },
    { id: 'NV024', name: 'Đinh Công Thành', department: 'IT', role: 'System Admin', salary: 20000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV025', name: 'Lưu Ngọc Ánh', department: 'HR', role: 'HR Intern', salary: 4500000, status: 'Đang làm', attendance: 22, },
    { id: 'NV026', name: 'Mai Tiến Dũng', department: 'Operations', role: 'Supply Chain Analyst', salary: 18000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV027', name: 'Tô Hoài Nam', department: 'IT', role: 'Business Analyst', salary: 21000000, status: 'Đang làm', attendance: 23, },
    { id: 'NV028', name: 'Nguyễn Phương Linh', department: 'Marketing', role: 'Graphic Designer', salary: 15000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV029', name: 'Trần Minh Hoàng', department: 'Sales', role: 'Key Account Manager', salary: 28000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV030', name: 'Lê Diệu Linh', department: 'Accounting', role: 'Financial Analyst', salary: 20000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV031', name: 'Vũ Quốc Trung', department: 'IT', role: 'Data Scientist', salary: 30000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV032', name: 'Đặng Thu Trang', department: 'HR', role: 'Training Specialist', salary: 17000000, status: 'Đang làm', attendance: 23, },
    { id: 'NV033', name: 'Hoàng Minh Đức', department: 'Operations', role: 'Operations Executive', salary: 13000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV034', name: 'Nguyễn Khánh Ly', department: 'Marketing', role: 'Social Media Manager', salary: 20000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV035', name: 'Phan Anh Tuấn', department: 'IT', role: 'Team Leader', salary: 38000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV036', name: 'Trần Ngọc Diệp', department: 'Sales', role: 'Sales Admin', salary: 10000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV037', name: 'Lê Quang Huy', department: 'Accounting', role: 'Tax Accountant', salary: 17000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV038', name: 'Võ Thị Mỹ Duyên', department: 'HR', role: 'HR Generalist', salary: 16000000, status: 'Đang làm', attendance: 23, },
    { id: 'NV039', name: 'Đỗ Minh Hiếu', department: 'IT', role: 'Frontend Developer', salary: 18000000, status: 'Đang làm', attendance: 22, },
    { id: 'NV040', name: 'Nguyễn Thị Kim Chi', department: 'Marketing', role: 'Event Coordinator', salary: 14000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV041', name: 'Trần Quốc Toản', department: 'Operations', role: 'Warehouse Manager', salary: 22000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV042', name: 'Lê Thúy Hằng', department: 'Sales', role: 'Telesales', salary: 9000000, status: 'Nghỉ việc', attendance: 20, },
    { id: 'NV043', name: 'Phạm Văn Đồng', department: 'IT', role: 'Backend Developer', salary: 19000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV044', name: 'Hoàng Thị Thu', department: 'Accounting', role: 'Bookkeeper', salary: 12000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV045', name: 'Nguyễn Minh Châu', department: 'HR', role: 'HR Director', salary: 50000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV046', name: 'Vũ Đức Thắng', department: 'Marketing', role: 'Brand Manager', salary: 33000000, status: 'Đang làm', attendance: 25, },
    { id: 'NV047', name: 'Đặng Bảo An', department: 'IT', role: 'Fullstack Developer', salary: 23000000, status: 'Đang làm', attendance: 23, },
    { id: 'NV048', name: 'Lê Minh Nhật', department: 'Sales', role: 'Sales Director', salary: 60000000, status: 'Đang làm', attendance: 26, },
    { id: 'NV049', name: 'Trần Thị Thùy Linh', department: 'Operations', role: 'Purchasing Specialist', salary: 16000000, status: 'Đang làm', attendance: 24, },
    { id: 'NV050', name: 'Nguyễn Hoàng Long', department: 'IT', role: 'IT Director', salary: 70000000, status: 'Đang làm', attendance: 25, },
];